export const MATCHES = [
  // time uses Mexico City time (America/Mexico_City) for locking picks.
  { id: 1, stage: 'Grupo A', group: 'A', date: '11 junio 2026', time: '13:00', home: 'Mexico', away: 'South Africa', venue: 'Estadio Azteca', city: 'Mexico City' },
  { id: 2, stage: 'Grupo A', group: 'A', date: '11 junio 2026', time: '20:00', home: 'South Korea', away: 'Czechia', venue: 'Estadio Akron', city: 'Zapopan' },
  { id: 3, stage: 'Grupo B', group: 'B', date: '12 junio 2026', time: '13:00', home: 'Canada', away: 'Bosnia and Herzegovina', venue: 'BMO Field', city: 'Toronto' },
  { id: 4, stage: 'Grupo D', group: 'D', date: '12 junio 2026', time: '19:00', home: 'United States', away: 'Paraguay', venue: 'SoFi Stadium', city: 'Inglewood' },
  { id: 5, stage: 'Grupo B', group: 'B', date: '13 junio 2026', time: '13:00', home: 'Qatar', away: 'Switzerland', venue: "Levi's Stadium", city: 'Santa Clara' },
  { id: 6, stage: 'Grupo C', group: 'C', date: '13 junio 2026', time: '16:00', home: 'Brazil', away: 'Morocco', venue: 'Gillette Stadium', city: 'Foxborough' },
  { id: 7, stage: 'Grupo C', group: 'C', date: '13 junio 2026', time: '19:00', home: 'Haiti', away: 'Scotland', venue: 'MetLife Stadium', city: 'East Rutherford' },
  { id: 8, stage: 'Grupo D', group: 'D', date: '13 junio 2026', time: '22:00', home: 'Australia', away: 'Turkiye', venue: 'BC Place', city: 'Vancouver' },
  { id: 9, stage: 'Grupo E', group: 'E', date: '14 junio 2026', time: '17:00', home: 'Ivory Coast', away: 'Ecuador', venue: 'Lincoln Financial Field', city: 'Philadelphia' },
  { id: 10, stage: 'Grupo E', group: 'E', date: '14 junio 2026', time: '11:00', home: 'Germany', away: 'Curacao', venue: 'NRG Stadium', city: 'Houston' },
  { id: 11, stage: 'Grupo F', group: 'F', date: '14 junio 2026', time: '14:00', home: 'Netherlands', away: 'Japan', venue: 'AT&T Stadium', city: 'Arlington' },
  { id: 12, stage: 'Grupo F', group: 'F', date: '14 junio 2026', time: '20:00', home: 'Sweden', away: 'Tunisia', venue: 'Estadio BBVA', city: 'Guadalupe' },
  { id: 13, stage: 'Grupo G', group: 'G', date: '15 junio 2026', time: '19:00', home: 'Iran', away: 'New Zealand', venue: 'SoFi Stadium', city: 'Inglewood' },
  { id: 14, stage: 'Grupo G', group: 'G', date: '15 junio 2026', time: '13:00', home: 'Belgium', away: 'Egypt', venue: 'Lumen Field', city: 'Seattle' },
  { id: 15, stage: 'Grupo H', group: 'H', date: '15 junio 2026', time: '16:00', home: 'Saudi Arabia', away: 'Uruguay', venue: 'Hard Rock Stadium', city: 'Miami Gardens' },
  { id: 16, stage: 'Grupo H', group: 'H', date: '15 junio 2026', time: '10:00', home: 'Spain', away: 'Cape Verde', venue: 'Mercedes-Benz Stadium', city: 'Atlanta' },
  { id: 17, stage: 'Grupo I', group: 'I', date: '16 junio 2026', time: '13:00', home: 'France', away: 'Senegal', venue: 'MetLife Stadium', city: 'East Rutherford' },
  { id: 18, stage: 'Grupo I', group: 'I', date: '16 junio 2026', time: '16:00', home: 'Iraq', away: 'Norway', venue: 'Gillette Stadium', city: 'Foxborough' },
  { id: 19, stage: 'Grupo J', group: 'J', date: '16 junio 2026', time: '19:00', home: 'Argentina', away: 'Algeria', venue: 'Arrowhead Stadium', city: 'Kansas City' },
  { id: 20, stage: 'Grupo J', group: 'J', date: '16 junio 2026', time: '22:00', home: 'Austria', away: 'Jordan', venue: "Levi's Stadium", city: 'Santa Clara' },
  { id: 21, stage: 'Grupo K', group: 'K', date: '17 junio 2026', time: '11:00', home: 'Portugal', away: 'DR Congo', venue: 'NRG Stadium', city: 'Houston' },
  { id: 22, stage: 'Grupo K', group: 'K', date: '17 junio 2026', time: '20:00', home: 'Uzbekistan', away: 'Colombia', venue: 'Estadio Azteca', city: 'Mexico City' },
  { id: 23, stage: 'Grupo L', group: 'L', date: '17 junio 2026', time: '17:00', home: 'Ghana', away: 'Panama', venue: 'BMO Field', city: 'Toronto' },
  { id: 24, stage: 'Grupo L', group: 'L', date: '17 junio 2026', time: '14:00', home: 'England', away: 'Croatia', venue: 'AT&T Stadium', city: 'Arlington' },
  { id: 25, stage: 'Grupo A', group: 'A', date: '18 junio 2026', time: '10:00', home: 'Czechia', away: 'South Africa', venue: 'Mercedes-Benz Stadium', city: 'Atlanta' },
  { id: 26, stage: 'Grupo A', group: 'A', date: '18 junio 2026', time: '19:00', home: 'Mexico', away: 'South Korea', venue: 'Estadio Akron', city: 'Zapopan' },
  { id: 27, stage: 'Grupo B', group: 'B', date: '18 junio 2026', time: '13:00', home: 'Switzerland', away: 'Bosnia and Herzegovina', venue: 'SoFi Stadium', city: 'Inglewood' },
  { id: 28, stage: 'Grupo B', group: 'B', date: '18 junio 2026', time: '16:00', home: 'Canada', away: 'Qatar', venue: 'BC Place', city: 'Vancouver' },
  { id: 29, stage: 'Grupo C', group: 'C', date: '19 junio 2026', time: '16:00', home: 'Scotland', away: 'Morocco', venue: 'Lincoln Financial Field', city: 'Philadelphia' },
  { id: 30, stage: 'Grupo C', group: 'C', date: '19 junio 2026', time: '18:30', home: 'Brazil', away: 'Haiti', venue: 'Gillette Stadium', city: 'Foxborough' },
  { id: 31, stage: 'Grupo D', group: 'D', date: '19 junio 2026', time: '21:00', home: 'Turkiye', away: 'Paraguay', venue: "Levi's Stadium", city: 'Santa Clara' },
  { id: 32, stage: 'Grupo D', group: 'D', date: '19 junio 2026', time: '13:00', home: 'United States', away: 'Australia', venue: 'Lumen Field', city: 'Seattle' },
  { id: 33, stage: 'Grupo E', group: 'E', date: '20 junio 2026', time: '14:00', home: 'Germany', away: 'Ivory Coast', venue: 'BMO Field', city: 'Toronto' },
  { id: 34, stage: 'Grupo E', group: 'E', date: '20 junio 2026', time: '18:00', home: 'Ecuador', away: 'Curacao', venue: 'Arrowhead Stadium', city: 'Kansas City' },
  { id: 35, stage: 'Grupo F', group: 'F', date: '20 junio 2026', time: '11:00', home: 'Netherlands', away: 'Sweden', venue: 'NRG Stadium', city: 'Houston' },
  { id: 36, stage: 'Grupo F', group: 'F', date: '20 junio 2026', time: '22:00', home: 'Tunisia', away: 'Japan', venue: 'Estadio BBVA', city: 'Guadalupe' },
  { id: 37, stage: 'Grupo G', group: 'G', date: '21 junio 2026', time: '13:00', home: 'Belgium', away: 'Iran', venue: 'SoFi Stadium', city: 'Inglewood' },
  { id: 38, stage: 'Grupo G', group: 'G', date: '21 junio 2026', time: '19:00', home: 'New Zealand', away: 'Egypt', venue: 'BC Place', city: 'Vancouver' },
  { id: 39, stage: 'Grupo H', group: 'H', date: '21 junio 2026', time: '16:00', home: 'Uruguay', away: 'Cape Verde', venue: 'Hard Rock Stadium', city: 'Miami Gardens' },
  { id: 40, stage: 'Grupo H', group: 'H', date: '21 junio 2026', time: '10:00', home: 'Spain', away: 'Saudi Arabia', venue: 'Mercedes-Benz Stadium', city: 'Atlanta' },
  { id: 41, stage: 'Grupo I', group: 'I', date: '22 junio 2026', time: '18:00', home: 'Norway', away: 'Senegal', venue: 'MetLife Stadium', city: 'East Rutherford' },
  { id: 42, stage: 'Grupo I', group: 'I', date: '22 junio 2026', time: '15:00', home: 'France', away: 'Iraq', venue: 'Lincoln Financial Field', city: 'Philadelphia' },
  { id: 43, stage: 'Grupo J', group: 'J', date: '22 junio 2026', time: '11:00', home: 'Argentina', away: 'Austria', venue: 'AT&T Stadium', city: 'Arlington' },
  { id: 44, stage: 'Grupo J', group: 'J', date: '22 junio 2026', time: '21:00', home: 'Jordan', away: 'Algeria', venue: "Levi's Stadium", city: 'Santa Clara' },
  { id: 45, stage: 'Grupo K', group: 'K', date: '23 junio 2026', time: '11:00', home: 'Portugal', away: 'Uzbekistan', venue: 'NRG Stadium', city: 'Houston' },
  { id: 46, stage: 'Grupo K', group: 'K', date: '23 junio 2026', time: '20:00', home: 'Colombia', away: 'DR Congo', venue: 'Estadio Akron', city: 'Zapopan' },
  { id: 47, stage: 'Grupo L', group: 'L', date: '23 junio 2026', time: '14:00', home: 'England', away: 'Ghana', venue: 'Gillette Stadium', city: 'Foxborough' },
  { id: 48, stage: 'Grupo L', group: 'L', date: '23 junio 2026', time: '17:00', home: 'Panama', away: 'Croatia', venue: 'BMO Field', city: 'Toronto' },
  { id: 49, stage: 'Grupo A', group: 'A', date: '24 junio 2026', time: '19:00', home: 'Czechia', away: 'Mexico', venue: 'Estadio Azteca', city: 'Mexico City' },
  { id: 50, stage: 'Grupo A', group: 'A', date: '24 junio 2026', time: '19:00', home: 'South Africa', away: 'South Korea', venue: 'Estadio BBVA', city: 'Guadalupe' },
  { id: 51, stage: 'Grupo B', group: 'B', date: '24 junio 2026', time: '13:00', home: 'Switzerland', away: 'Canada', venue: 'BC Place', city: 'Vancouver' },
  { id: 52, stage: 'Grupo B', group: 'B', date: '24 junio 2026', time: '13:00', home: 'Bosnia and Herzegovina', away: 'Qatar', venue: 'Lumen Field', city: 'Seattle' },
  { id: 53, stage: 'Grupo C', group: 'C', date: '24 junio 2026', time: '16:00', home: 'Scotland', away: 'Brazil', venue: 'Hard Rock Stadium', city: 'Miami Gardens' },
  { id: 54, stage: 'Grupo C', group: 'C', date: '24 junio 2026', time: '16:00', home: 'Morocco', away: 'Haiti', venue: 'Mercedes-Benz Stadium', city: 'Atlanta' },
  { id: 55, stage: 'Grupo D', group: 'D', date: '25 junio 2026', time: '20:00', home: 'Turkiye', away: 'United States', venue: 'SoFi Stadium', city: 'Inglewood' },
  { id: 56, stage: 'Grupo D', group: 'D', date: '25 junio 2026', time: '20:00', home: 'Paraguay', away: 'Australia', venue: "Levi's Stadium", city: 'Santa Clara' },
  { id: 57, stage: 'Grupo E', group: 'E', date: '25 junio 2026', time: '14:00', home: 'Curacao', away: 'Ivory Coast', venue: 'Lincoln Financial Field', city: 'Philadelphia' },
  { id: 58, stage: 'Grupo E', group: 'E', date: '25 junio 2026', time: '14:00', home: 'Ecuador', away: 'Germany', venue: 'MetLife Stadium', city: 'East Rutherford' },
  { id: 59, stage: 'Grupo F', group: 'F', date: '25 junio 2026', time: '17:00', home: 'Japan', away: 'Sweden', venue: 'AT&T Stadium', city: 'Arlington' },
  { id: 60, stage: 'Grupo F', group: 'F', date: '25 junio 2026', time: '17:00', home: 'Tunisia', away: 'Netherlands', venue: 'Arrowhead Stadium', city: 'Kansas City' },
  { id: 61, stage: 'Grupo G', group: 'G', date: '26 junio 2026', time: '21:00', home: 'Egypt', away: 'Iran', venue: 'Lumen Field', city: 'Seattle' },
  { id: 62, stage: 'Grupo G', group: 'G', date: '26 junio 2026', time: '21:00', home: 'New Zealand', away: 'Belgium', venue: 'BC Place', city: 'Vancouver' },
  { id: 63, stage: 'Grupo H', group: 'H', date: '26 junio 2026', time: '18:00', home: 'Cape Verde', away: 'Saudi Arabia', venue: 'NRG Stadium', city: 'Houston' },
  { id: 64, stage: 'Grupo H', group: 'H', date: '26 junio 2026', time: '18:00', home: 'Uruguay', away: 'Spain', venue: 'Estadio Akron', city: 'Zapopan' },
  { id: 65, stage: 'Grupo I', group: 'I', date: '26 junio 2026', time: '13:00', home: 'Norway', away: 'France', venue: 'Gillette Stadium', city: 'Foxborough' },
  { id: 66, stage: 'Grupo I', group: 'I', date: '26 junio 2026', time: '13:00', home: 'Senegal', away: 'Iraq', venue: 'BMO Field', city: 'Toronto' },
  { id: 67, stage: 'Grupo J', group: 'J', date: '27 junio 2026', time: '20:00', home: 'Algeria', away: 'Austria', venue: 'Arrowhead Stadium', city: 'Kansas City' },
  { id: 68, stage: 'Grupo J', group: 'J', date: '27 junio 2026', time: '20:00', home: 'Jordan', away: 'Argentina', venue: 'AT&T Stadium', city: 'Arlington' },
  { id: 69, stage: 'Grupo K', group: 'K', date: '27 junio 2026', time: '17:30', home: 'Colombia', away: 'Portugal', venue: 'Hard Rock Stadium', city: 'Miami Gardens' },
  { id: 70, stage: 'Grupo K', group: 'K', date: '27 junio 2026', time: '17:30', home: 'DR Congo', away: 'Uzbekistan', venue: 'Mercedes-Benz Stadium', city: 'Atlanta' },
  { id: 71, stage: 'Grupo L', group: 'L', date: '27 junio 2026', time: '15:00', home: 'Panama', away: 'England', venue: 'MetLife Stadium', city: 'East Rutherford' },
  { id: 72, stage: 'Grupo L', group: 'L', date: '27 junio 2026', time: '15:00', home: 'Croatia', away: 'Ghana', venue: 'Lincoln Financial Field', city: 'Philadelphia' },
  { id: 73, stage: 'Ronda de 32', group: '', date: '28 junio 2026', time: '13:00', home: 'Runner-up Group A', away: 'Runner-up Group B', venue: 'SoFi Stadium', city: 'Inglewood' },
  { id: 74, stage: 'Ronda de 32', group: '', date: '29 junio 2026', time: '14:30', home: 'Winner Group E', away: '3rd Group A/B/C/D/F', venue: 'Gillette Stadium', city: 'Foxborough' },
  { id: 75, stage: 'Ronda de 32', group: '', date: '29 junio 2026', time: '19:00', home: 'Winner Group F', away: 'Runner-up Group C', venue: 'Estadio BBVA', city: 'Guadalupe' },
  { id: 76, stage: 'Ronda de 32', group: '', date: '29 junio 2026', time: '11:00', home: 'Winner Group C', away: 'Runner-up Group F', venue: 'NRG Stadium', city: 'Houston' },
  { id: 77, stage: 'Ronda de 32', group: '', date: '30 junio 2026', time: '15:00', home: 'Winner Group I', away: '3rd Group C/D/F/G/H', venue: 'MetLife Stadium', city: 'East Rutherford' },
  { id: 78, stage: 'Ronda de 32', group: '', date: '30 junio 2026', time: '11:00', home: 'Runner-up Group E', away: 'Runner-up Group I', venue: 'AT&T Stadium', city: 'Arlington' },
  { id: 79, stage: 'Ronda de 32', group: '', date: '30 junio 2026', time: '19:00', home: 'Winner Group A', away: '3rd Group C/E/F/H/I', venue: 'Estadio Azteca', city: 'Mexico City' },
  { id: 80, stage: 'Ronda de 32', group: '', date: '1 julio 2026', time: '10:00', home: 'Winner Group L', away: '3rd Group E/H/I/J/K', venue: 'Mercedes-Benz Stadium', city: 'Atlanta' },
  { id: 81, stage: 'Ronda de 32', group: '', date: '1 julio 2026', time: '18:00', home: 'Winner Group D', away: '3rd Group B/E/F/I/J', venue: "Levi's Stadium", city: 'Santa Clara' },
  { id: 82, stage: 'Ronda de 32', group: '', date: '1 julio 2026', time: '14:00', home: 'Winner Group G', away: '3rd Group A/E/H/I/J', venue: 'Lumen Field', city: 'Seattle' },
  { id: 83, stage: 'Ronda de 32', group: '', date: '2 julio 2026', time: '17:00', home: 'Runner-up Group K', away: 'Runner-up Group L', venue: 'BMO Field', city: 'Toronto' },
  { id: 84, stage: 'Ronda de 32', group: '', date: '2 julio 2026', time: '13:00', home: 'Winner Group H', away: 'Runner-up Group J', venue: 'SoFi Stadium', city: 'Inglewood' },
  { id: 85, stage: 'Ronda de 32', group: '', date: '2 julio 2026', time: '21:00', home: 'Winner Group B', away: '3rd Group E/F/G/I/J', venue: 'BC Place', city: 'Vancouver' },
  { id: 86, stage: 'Ronda de 32', group: '', date: '3 julio 2026', time: '16:00', home: 'Winner Group J', away: 'Runner-up Group H', venue: 'Hard Rock Stadium', city: 'Miami Gardens' },
  { id: 87, stage: 'Ronda de 32', group: '', date: '3 julio 2026', time: '19:30', home: 'Winner Group K', away: '3rd Group D/E/I/J/L', venue: 'Arrowhead Stadium', city: 'Kansas City' },
  { id: 88, stage: 'Ronda de 32', group: '', date: '3 julio 2026', time: '12:00', home: 'Runner-up Group D', away: 'Runner-up Group G', venue: 'AT&T Stadium', city: 'Arlington' },
  { id: 89, stage: 'Octavos', group: '', date: '4 julio 2026', time: '15:00', home: 'Winner Match 74', away: 'Winner Match 77', venue: 'Lincoln Financial Field', city: 'Philadelphia' },
  { id: 90, stage: 'Octavos', group: '', date: '4 julio 2026', time: '11:00', home: 'Winner Match 73', away: 'Winner Match 75', venue: 'NRG Stadium', city: 'Houston' },
  { id: 91, stage: 'Octavos', group: '', date: '5 julio 2026', time: '14:00', home: 'Winner Match 76', away: 'Winner Match 78', venue: 'MetLife Stadium', city: 'East Rutherford' },
  { id: 92, stage: 'Octavos', group: '', date: '5 julio 2026', time: '18:00', home: 'Winner Match 79', away: 'Winner Match 80', venue: 'Estadio Azteca', city: 'Mexico City' },
  { id: 93, stage: 'Octavos', group: '', date: '6 julio 2026', time: '13:00', home: 'Winner Match 83', away: 'Winner Match 84', venue: 'AT&T Stadium', city: 'Arlington' },
  { id: 94, stage: 'Octavos', group: '', date: '6 julio 2026', time: '18:00', home: 'Winner Match 81', away: 'Winner Match 82', venue: 'Lumen Field', city: 'Seattle' },
  { id: 95, stage: 'Octavos', group: '', date: '7 julio 2026', time: '10:00', home: 'Winner Match 86', away: 'Winner Match 88', venue: 'Mercedes-Benz Stadium', city: 'Atlanta' },
  { id: 96, stage: 'Octavos', group: '', date: '7 julio 2026', time: '14:00', home: 'Winner Match 85', away: 'Winner Match 87', venue: 'BC Place', city: 'Vancouver' },
  { id: 97, stage: 'Cuartos', group: '', date: '9 julio 2026', time: '14:00', home: 'Winner Match 89', away: 'Winner Match 90', venue: 'Gillette Stadium', city: 'Foxborough' },
  { id: 98, stage: 'Cuartos', group: '', date: '10 julio 2026', time: '13:00', home: 'Winner Match 93', away: 'Winner Match 94', venue: 'SoFi Stadium', city: 'Inglewood' },
  { id: 99, stage: 'Cuartos', group: '', date: '11 julio 2026', time: '15:00', home: 'Winner Match 91', away: 'Winner Match 92', venue: 'Hard Rock Stadium', city: 'Miami Gardens' },
  { id: 100, stage: 'Cuartos', group: '', date: '11 julio 2026', time: '19:00', home: 'Winner Match 95', away: 'Winner Match 96', venue: 'Arrowhead Stadium', city: 'Kansas City' },
  { id: 101, stage: 'Semifinal', group: '', date: '14 julio 2026', time: '13:00', home: 'Winner Match 97', away: 'Winner Match 98', venue: 'AT&T Stadium', city: 'Arlington' },
  { id: 102, stage: 'Semifinal', group: '', date: '15 julio 2026', time: '13:00', home: 'Winner Match 99', away: 'Winner Match 100', venue: 'Mercedes-Benz Stadium', city: 'Atlanta' },
  { id: 103, stage: 'Tercer lugar', group: '', date: '18 julio 2026', time: '15:00', home: 'Loser Match 101', away: 'Loser Match 102', venue: 'Hard Rock Stadium', city: 'Miami Gardens' },
  { id: 104, stage: 'Final', group: '', date: '19 julio 2026', time: '13:00', home: 'Winner Match 101', away: 'Winner Match 102', venue: 'MetLife Stadium', city: 'East Rutherford' },
];
